name: Build
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # every day 1pm (UTC)
    - cron: '0 13 * * *'

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Docker Build Cache
        uses: actions/cache@v2
        with:
          path: /tmp/docker-builds
          key: ${{ runner.os }}-${{ hashFiles('**/docker/build.sh') }}-${{ hashFiles('**/docker/liberica-base/Dockerfile') }}-${{ hashFiles('**/docker/liberica-jre/Dockerfile') }}-${{ hashFiles('**/.github/workflows/build.yaml') }}

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build docker images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker/build.sh push
          else
            docker/build.sh
          fi
